/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as JobDescriptionRouteImport } from './routes/job-description'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AddCandidateRouteImport } from './routes/add-candidate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CandidatesIndexRouteImport } from './routes/candidates.index'
import { Route as CandidatesIdRouteImport } from './routes/candidates.$id'

const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const JobDescriptionRoute = JobDescriptionRouteImport.update({
  id: '/job-description',
  path: '/job-description',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AddCandidateRoute = AddCandidateRouteImport.update({
  id: '/add-candidate',
  path: '/add-candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesIndexRoute = CandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesIdRoute = CandidatesIdRouteImport.update({
  id: '/candidates/$id',
  path: '/candidates/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-candidate': typeof AddCandidateRoute
  '/analytics': typeof AnalyticsRoute
  '/job-description': typeof JobDescriptionRoute
  '/results': typeof ResultsRoute
  '/candidates/$id': typeof CandidatesIdRoute
  '/candidates/': typeof CandidatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-candidate': typeof AddCandidateRoute
  '/analytics': typeof AnalyticsRoute
  '/job-description': typeof JobDescriptionRoute
  '/results': typeof ResultsRoute
  '/candidates/$id': typeof CandidatesIdRoute
  '/candidates': typeof CandidatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-candidate': typeof AddCandidateRoute
  '/analytics': typeof AnalyticsRoute
  '/job-description': typeof JobDescriptionRoute
  '/results': typeof ResultsRoute
  '/candidates/$id': typeof CandidatesIdRoute
  '/candidates/': typeof CandidatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-candidate'
    | '/analytics'
    | '/job-description'
    | '/results'
    | '/candidates/$id'
    | '/candidates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-candidate'
    | '/analytics'
    | '/job-description'
    | '/results'
    | '/candidates/$id'
    | '/candidates'
  id:
    | '__root__'
    | '/'
    | '/add-candidate'
    | '/analytics'
    | '/job-description'
    | '/results'
    | '/candidates/$id'
    | '/candidates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddCandidateRoute: typeof AddCandidateRoute
  AnalyticsRoute: typeof AnalyticsRoute
  JobDescriptionRoute: typeof JobDescriptionRoute
  ResultsRoute: typeof ResultsRoute
  CandidatesIdRoute: typeof CandidatesIdRoute
  CandidatesIndexRoute: typeof CandidatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-description': {
      id: '/job-description'
      path: '/job-description'
      fullPath: '/job-description'
      preLoaderRoute: typeof JobDescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-candidate': {
      id: '/add-candidate'
      path: '/add-candidate'
      fullPath: '/add-candidate'
      preLoaderRoute: typeof AddCandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/': {
      id: '/candidates/'
      path: '/candidates'
      fullPath: '/candidates/'
      preLoaderRoute: typeof CandidatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/$id': {
      id: '/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof CandidatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddCandidateRoute: AddCandidateRoute,
  AnalyticsRoute: AnalyticsRoute,
  JobDescriptionRoute: JobDescriptionRoute,
  ResultsRoute: ResultsRoute,
  CandidatesIdRoute: CandidatesIdRoute,
  CandidatesIndexRoute: CandidatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
